name: Docker Image CI

on:
  push:
    branches: [ main ]
#   pull_request:
#     branches: [ main ]

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Inspect builder
        run: |
          echo "Name:      ${{ steps.buildx.outputs.name }}"
          echo "Endpoint:  ${{ steps.buildx.outputs.endpoint }}"
          echo "Status:    ${{ steps.buildx.outputs.status }}"
          echo "Flags:     ${{ steps.buildx.outputs.flags }}"
          echo "Platforms: ${{ steps.buildx.outputs.platforms }}"    
      - name: Docker Login
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: | 
          echo $DOCKER_TOKEN | docker login -u $DOCKER_USER --password-stdin
      - name: Run Docker Multi-Platform Build and Push
        run: |
          docker buildx build --platform linux/arm64,linux/amd64 --tag justincoded/storm:$(date +%s) --push ./storm/1.2.4
   